### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by ulivz** [meteorlxy/vuepress-plugin-smooth-scroll#1]
![vuepress-plugin-smooth-scroll-issue](https://user-images.githubusercontent.com/23133919/53379252-d7885780-39a3-11e9-959a-5a7bc18b023a.gif)

**Comment by meteorlxy** [comment]
@ulivz 

Is that the problem of compatibility with `@vuepress/plugin-active-header-links`?

![image](https://user-images.githubusercontent.com/18205362/53386060-a0be3b80-39bb-11e9-8ee1-3cba425f3e59.png)

One possible solution is to use `debounce` instead of `throttle` in `@vuepress/plugin-active-header-links`.

But I'm afraid if the official plugin will try to solve this compatible problem.

**Comment by shigma** [comment]
> But I'm afraid if the official plugin will try to solve this compatible problem.

Still, at least you should try to open an issue. 😆

**Comment by meteorlxy** [comment]
fixed in https://github.com/vuejs/vuepress/pull/1881
